# Generated by Django 4.2.7 on 2024-03-09 21:09

from django.db import migrations
from django.db import models
import django.db.models.deletion

import billing.models.billing


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BillingTask",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("public_id", models.UUIDField(unique=True)),
                ("assignee_public_id", models.UUIDField()),
                ("status", models.CharField(max_length=100)),
                ("cost_assign", models.DecimalField(decimal_places=2, default=billing.models.billing.get_assign_cost, editable=False, max_digits=10)),
                ("cost_complete", models.DecimalField(decimal_places=2, default=billing.models.billing.get_complete_cost, editable=False, max_digits=10)),
                ("title", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BillingUser",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("public_id", models.UUIDField(unique=True)),
                ("role", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BillingAccount",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="billing.billinguser")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
