# Generated by Django 4.2.7 on 2024-03-05 19:44

import uuid

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("public_id", models.UUIDField(default=uuid.UUID("15e909b3-2c24-49e4-b57c-8fb83a101873"), editable=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("cost_assign", models.DecimalField(decimal_places=2, default=16.05, editable=False, max_digits=10)),
                ("cost_complete", models.DecimalField(decimal_places=2, default=33.69, max_digits=10)),
                ("status", models.CharField(choices=[("ASSIGNED", "Assigned"), ("COMPLETED", "Completed")], default="ASSIGNED", max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskUser",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("public_id", models.UUIDField(unique=True)),
                ("role", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("status", models.CharField(choices=[("ASSIGNED", "Assigned"), ("COMPLETED", "Completed")], default="ASSIGNED", max_length=100)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tasks.task")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskCost",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("cost_assign", models.DecimalField(decimal_places=2, default=19.07, max_digits=10)),
                ("cost_complete", models.DecimalField(decimal_places=2, default=30.43, max_digits=10)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tasks.task")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="task",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tasks.taskuser"),
        ),
    ]
